require:
  - rubocop-minitest
  - rubocop-rails
  - rubocop-rake
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1.0
  NewCops: enable
  Exclude:
    - config/initializers/simple_form_bootstrap.rb
    - config/initializers/simple_form.rb
    - bin/**/*
    - vendor/bundle/**/*
    - db/schema.rb
    - node_modules/**/*
    - tmp/**/*

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Metrics/BlockLength:
  Exclude:
    - config/**/*

Rails/NotNullColumn:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets
