require:
  - rubocop-minitest
  - rubocop-rails
  - rubocop-rake
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1.0
  NewCops: enable
  Exclude:
    - db/schema.rb
    - tmp/**/*
    - bin/**/*
    - vendor/**/*
    - node_modules/**/*
    - config/**/*

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - test/**/*

Metrics/ClassLength:
  Exclude:
    - test/**/*

Minitest/MultipleAssertions:
  Exclude:
    - test/system/**/*

Rails/NotNullColumn:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: true

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets
